"Resource\OptionsSubPortal.res"
{
	"PortalFunnel"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"PortalFunnel"
		"xpos"		"28"
		"ypos"		"28"
		"wide"		"148"
		"tall"		"28"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GameUI_PortalFunnel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"default"		"0"
	}
	"SwtichPortalGunModel"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"SwtichPortalGunModel"
		"xpos"		"28"
		"ypos"		"56"
		"tooltiptext"		"Switch between 2005 and 2006 portal gun"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"4"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Toggle Alt Portal gun"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"command"		"cl_portalgun_altmodel 1"
		"default"		"0"
	}
	"Regeneration"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"Regeneration"
		"xpos"		"180"
		"ypos"		"56"
		"tooltiptext"		"Toggle Regeneration"
		"wide"		"160"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"4"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Toggle Regeneration"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"command"		"cl_portalgun_altmodel 1"
		"default"		"0"
	}
	"PortalDepth"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"PortalDepth"
		"xpos"		"33"
		"ypos"		"106"
		"wide"		"175"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Portal Funnel label"
	{
		"ControlName"		"Label"
		"fieldName"		"Portal Funnel label"
		"xpos"		"159"
		"ypos"		"31"
		"wide"		"320"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PortalFunnelLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"PortalDepthLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PortalDepthLabel"
		"xpos"		"35"
		"ypos"		"82"
		"wide"		"179"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_PortalDepthLabel"
		"textAlignment"		"west"
		"associate"		"PortalDepth"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"MessageBox1"
	{
		"ControlName"		"MessageBox"
		"fieldName"		"MessageBox1"
		"xpos"		"414"
		"ypos"		"326"
		"wide"		"195"
		"tall"		"116"
		"AutoResize"		"0"
		"PinCorner"		"4"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
